config/routes.rb
Travelgift::Application.routes.draw do

  resources :homes
  resources :hotels, :only => [:index, :show] do
      collection do
        get :search
      end
  end

  root :to => 'homes#index'
end

app/models/hotels.rb
class Hotels < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  respond_to :html, :json
  # GET /hotels
  # GET /hotels.json
  def index
    #logger.debug "[debug]"
    #logger.debug params[:index].to_s
    #logger.debug params[:index][:city]

    #if params[:index] != nil
    #  options = {
    #    :apikey => EAN3_CONFIG["apikey"],
    #    :secret => EAN3_CONFIG["apikey"],
    #    :cid => EAN3_CONFIG["cid"],
    #    :minorRev => 12,
    #    :locale => "ja_JP",
    #    :currencyCode => "JPY",
    #    :debug => true
    #  }
    #  @client = Ean3::Client.new(options)
    #  params[:index][:numberOfResults] = 20
    #  logger.debug params[:index]
    #  @response = @client.getList(params[:index])
    #end

    #respond_to do |format|
    #  format.html
    #  format.json { render :json => @response }
    #end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    respond_to do |format|
      format.html
    end
  end

  def search
    if params[:index] != nil
      options = {
        :apikey => EAN3_CONFIG["apikey"],
        :secret => EAN3_CONFIG["apikey"],
        :cid => EAN3_CONFIG["cid"],
        :minorRev => 12,
        :locale => "ja_JP",
        :currencyCode => "JPY",
        :debug => true
      }
      @client = Ean3::Client.new(options)
      params[:index][:numberOfResults] = 20
      logger.debug params[:index]
      @response = @client.getList(params[:index])
    end

    respond_with do |format|
      format.html do
        if request.xhr?
          render :partial => 'results', :layout => false
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.haml
%p
  = link_to 'ホテルを検索する', :controller => 'hotels', :action => 'index'

app/views/hotels/_form.html.haml
%h2 検索条件

= form_for @hotel, :method => 'get', :url => search_hotels_path, :remote => true do |f|

  .field
    = f.label '到着日'
    = f.text_field :arrivalDate
  .field
    = f.label '出発日'
    = f.text_field :departureDate
  .field
    = f.label '地域'
    = f.text_field :city
  .action
    = f.submit '検索', :id => 'search_hotel_btn', :class => 'btn primary'

app/views/hotels/_results.html.haml
- if @response && @response.HotelListResopnse
  %h2 ホテル一覧

  %ul
    - for hotel in @response.HotelListResponse.HotelList.HotelSummary
      %li
        %p
          = hotel.name
        %p
          = hotel.address1
        %p
          hotel rating
        %span
          = hotel.hotelRating
        %p
          low rate
        %span
          = hotel.lowRate

app/views/hotels/index.html.haml
.container

  = render 'form'

  #results

:javascript
  $(function(){
    Hotels.init();
  });

app/views/hotels/show.html.haml
%h1 ホテル一覧

%p hoge
%ul
  - for hotel in @response.HotelListResponse.HotelList
    %li
      %p aaaaaaa
  %li
    %p テスト1
  %li
    %p テスト2

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travelgift</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "bootstrap.css" %>
  <%= stylesheet_link_tag    "jquery-ui-1.8.16.custom.css" %>
  <%= stylesheet_link_tag    "jquery.ui.1.8.16.ie.css" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-ui-1.8.16.custom.min.js" %>
  <%= javascript_include_tag "bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-fixed-top">
      <div class="cotainer">
          <div class="nav-collapse">
              <ul class="nav">
                  <li class="active"><a>テスト</a></li>
              </ul>
          </div>
      </div>
    </div>
<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fbid %><br />
    <%= f.text_field :fbid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Fbid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.fbid %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fbid:</b>
  <%= @user.fbid %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>